# Generated by Django 5.2.5 on 2025-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency_converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('converted_amount', models.FloatField(blank=True, null=True)),
                ('select_currency', models.CharField(blank=True, null=True)),
                ('converted_currency', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
